name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # 1. Стадия тестирования
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  # 2. Стадия сборки
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test  # сборка начнется только после успешных тестов
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t myapp .

  # 3. Стадия деплоя
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build  # деплой начнется только после успешной сборки
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 94.228.112.241 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh root@94.228.112.241 "cd /root/DevSecOps && git pull && docker-compose up -d"

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Debug SSH connection
        run: |
          ssh -v root@94.228.112.241
